// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import WordController from "./word_controller.js"
application.register("word", WordController)

import WordleController from "./wordle_controller.js"
application.register("wordle", WordleController)
